---
output: github_document
always_allow_html: true
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r echo=FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "README-"
)
```

# LabCalculateR

This is an R Shiny app to get basic laboratory tasks done with ease.



## Current features

|Feature                    |Function|
|---------------------------|--------|
|Calibration KPIs           |Calculates performance indicators for calibration data and generates calibration reports.
|Equidistant calibration    |Creates the dilution scheme for calibration standards, based on the lowest and highest concentration, the target volume, and the concentration of the stock solution.
|Concentration              |Calculates concentration or volume.
|Mole converter             |Calculates the molar mass of a compound and converts a given value from mol to gram.
|Skalar reagent calculator  |Calculates quantities of chemicals for the preparation of specific volumes of reagents for the Skalar BluVision Discrete Analyzer.
