---
title: "Nitrite BLUVISION® Water"
author: "Tellbüscher Anil Axel MSc."
date: "Issue 190325/99425691"
output: html_document
---

# General Method

## PRINCIPLE

Nitrite is determined by diazotizing with sulfanilamide and coupling with N-(1-naphthyl) ethylenediamine dihydrochloride to form a highly colored azo dye which is measured at 540 nm.

## LABORATORY FACILITIES

1. Maximum power consumption depending on the analyzer configuration, 2000 VA. Check voltage at the back of the instrument before installation.
2. Facilities for chemical wastes. Check environmental regulations for proper disposal of waste.

## PROCEDURE SAMPLE PREPARATION

1. Samples should be collected in plastic or glass bottles. All bottles must be thoroughly cleaned and rinsed with reagent water. Volume collected should be sufficient to ensure a representative sample, allow for replicate analysis (if required), and minimize waste disposal.
2. Samples must never be preserved with acid for the NO2 analysis.
3. Samples should be analyzed as soon as possible after collection. If storage is required for 1 – 2 days, freeze at -20°C or store at 4°C.

## INTERFERENCES

High alkalinity of samples may interfere with the analysis method. Neutralize with phosphoric acid. Amines, chloramines, thiosulfate, polyphosphate, Iron 3+, and oxidizing compounds may interfere.

# REAGENTS

## R1. Color reagent (500 ml)

**Required chemicals:**

- Phosphoric acid .......... 25 ml. H3PO4 (85%)
- Sulfanilamide .............. 2.5 g. C6H8N2O2S
- N-(1-naphthyl) ethylenediamine dihydrochloride ....... 0.125 g. C12H16Cl2N2
- Distilled water H2O

**Preparation:**

Dilute the hydrochloric acid in ≈ 400 ml of distilled water. Add the sulfanilamide and dissolve. Add the N-(1-naphthyl) ethylenediamine dihydrochloride and dissolve. Fill up to 500 ml with distilled water and mix.

**Note:**

Solution is stable for one month at 2 – 8 °C. Alternative: 25 ml H3PO4 (65%) can be replaced by 16.5 ml HCl (32%).

# CATALOGUE NUMBERS REQUIRED CHEMICALS

| Product                     | Supplier and catnr. |
|-----------------------------|---------------------|
| Phosphoric acid (85%)       | Merck 100573        |
| Hydrochloric acid (32%)     | Merck 100313        |
| Sulfanilamide               | Merck 108035        |
| N-(1-Naphthyl)ethylenediamine dihydrochloride | Merck 106237 |
| Sodium nitrite              | Merck 106549        |

# OPERATIONAL REMARKS AND TROUBLE SHOOTING

1. Persons using this Skalar method should be familiar with normal laboratory practice. This Skalar method does not purport to address all of the safety problems, if any, associated with its use. It is the responsibility of the user to establish appropriate safety and health practices and to ensure compliance with any national regulatory conditions.
2. The reagent bottles must be rinsed thoroughly with distilled water before refilling with fresh reagents. This is done to remove precipitation of microorganism and other interferences.
3. Avoid any turbidity in the reagents, filter if necessary.
4. It is advised to degas the distilled water (to remove the dissolved air) with one of the following procedures:
    - a. Degas the water with the use of a deaerator (vacuum);
    - b. Degas the water with a helium or nitrogen gas flow of approximately 20 liter/hour with the aid of a sparger for approximately 15 minutes.
5. Before starting a new analysis, it is recommended to rinse the diluters to remove any available air bubbles. This can be done by the menu on the BluVision: Tools, Rinse, Flush Diluters. Repeat this procedure if needed.
6. When a new cannister of distilled water is used flush the diluter to remove the visible air bubbles that’s inside the tubing.
7. When done with the BluVision it is advised to remove (or close the lids of) the reagents in the sample reagent disk and empty the cuvette waste. Don’t forget to remove the lid before starting a new analysis!

# REFERENCES

1. ISO 15923-1: Water quality — Determination of selected parameters by discrete analysis systems. Part 1: Ammonium, nitrate, nitrite, chloride, orthophosphate, sulfate and silicate with photometric detection
2. Standard Methods for the Examination of Water and Wastewater, 21st edition 2005, 1080 Reagent Water

# BLUVISION SETTINGS

| Parameter            | Sample | Reagent (R1) |
|----------------------|--------|--------------|
| Measurement point    | ☑      | ☑            |
| Pre-air volume (µl)  | 10     | 10           |
| Volume (µl)          | 450    | 50           |
| Additional volume (µl)| 20    | 20           |
| Pipetted as          | Extra  | Extra        |
| Inside rinsing volume (µl)| 1500 | 1500      |
| Outside rinsing volume (µl)| 3500 | 3500     |
| Reaction time (s)    | 0      | 360          |
| Stir time (s)        | 0      | 3            |
| Pickup speed (steps) | 5      | 5            |
| Dispense speed (steps)| 10    | 10           |

# OPERATIONAL SETTINGS

1. Wavelength: 540 nm
2. Reaction type: Colorization
3. Dilution type: Cuvette
4. Calibration type: ISO First order (ISO 8466-1)
5. Working standards
    - a. Stock concentration: 200 µg N/l
6. The sensitivity of the highest standard (100 µg N/l) ≈ 0.420 AU.

# STANDARD SOLUTIONS

## Stock solution 1000 mg N/l

**Required chemicals:**

- Sodium nitrite ......... 4.926 g. NaNO2
- Distilled water H2O

**Preparation:**

Dissolve the sodium nitrite in ≈ 800 ml of distilled water. Fill up to 1 liter with distilled water and mix.

**Note:**

Solution is stable for one month at room temperature.

## Stock solution 10 mg N/L

Dilute 1 ml of stock solution 1000 mg N/L to 100 ml with distilled water.

## Working stock solution 200 µg N/l

Dilute 2 ml stock solution 10 mg N/l to 100 ml with distilled water.

**Note:**

The stock standard is two times higher than the highest standard.

## Working standards

| Standard | Concentration (µg N/l) |
|----------|-------------------------|
| S1       | 1                       |
| S2       | 5                       |
| S3       | 10                      |
| S4       | 20                      |
| S5       | 40                      |
| S6       | 60                      |
| S7       | 80                      |
| S8       | 100                     |

# BLUVISION SETTINGS (0.05 – 2 mg N/l)

| Parameter            | Sample | Reagent (R1) |
|----------------------|--------|--------------|
| Measurement point    | ☑      | ☑            |
| Initial air volume (µl) | 10  | 10           |
| Liquid volume (µl)   | 50     | 50           |
| Extra liquid volume (µl) | 400 | 20           |
| Pipetted as          | Water  | Extra        |
| Inside rinsing volume (µl)| 1500 | 1500      |
| Outside rinsing volume (µl)| 3500 | 3500     |
| Reaction time (s)    | 0      | 360          |
| Stir time (s)        | 0      | 3            |
| Pickup speed (steps) | 5      | 5            |
| Dispense speed (steps)| 10    | 10           |

# OPERATIONAL SETTINGS

1. Wavelength: 540 nm
2. Reaction type: Colorization
3. Dilution type: Extra cuvette
4. Calibration type: ISO First order (ISO 8466-1)
5. Working standards
    - a. Stock concentration: 4 mg N/l
6. The sensitivity of the highest standard (2 mg N/l) ≈ 0.900 AU.

## Working stock solution 4 mg N/l

Dilute 0.4 ml stock solution 1000 mg N/l to 100 ml with distilled water.

**Note:**

The stock standard is two times higher than the highest standard.

## Working standards

| Standard | Concentration (mg N/l) |
|----------|-------------------------|
| S1       | 0.05                    |
| S2       | 0.10                    |
| S3       | 0.20                    |
| S4       | 0.40                    |
| S5       | 0.80                    |
| S6       | 1.20                    |
| S7       | 1.60                    |
| S8       | 2.00                    |
